extrinsic_matrix:
- - -0.009001091222497815
  - 0.9998101928762726
  - -0.017278847690595178
  - -0.03976227167673183
- - 0.7537106869084556
  - -0.004572142976465798
  - -0.6571904563736352
  - -0.8098749373637129
- - -0.6571447183054798
  - -0.018938683410239188
  - -0.7535264729748373
  - -0.913795321682261
- - 0.0
  - 0.0
  - 0.0
  - 1.0
