lidar:
  lidar_topic: sensors/livox/point_cloud2_sync
  frame_id: livox_frame

camera:
  image_topic: /camera/camera/color/image_raw
  projected_topic: /camera/projected_image
  image_size:
    width: 640
    height: 480
  frame_id: camera_color_frame

chessboard:
  pattern_size:
    rows: 7
    columns: 9
  square_size_meters: 0.41

general:
  config_folder: /home/moody/ros2_realsense_lidar_fusion/src/config
  data_folder: /home/moody/ros2_realsense_lidar_fusion/src/data
  correspondence_file: ros2_camera_lidar_fusion_correspondences.txt
  camera_intrinsic_calibration: camera_intrinsic_calibration.yaml
  camera_extrinsic_calibration: camera_extrinsic_calibration.yaml
  slop: 15
  max_file_saved: 30
  keyboard_listener: True
  get_intrinsics: True
  get_extrinsics: True